# Generated by Django 4.2.2 on 2023-06-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_mage_articleseries_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='mage',
            new_name='image',
        ),
    ]
